package profiler

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Build-time compilation of the embedded fingerprints.
//
// kitsune-gen compiles assets/fingerprints_data.json with the same code
// NewFromFile uses (compileFingerprints) and writes the result out as Go
// source: the patterns with their rewritten regex source, confidence,
// version and prefilter literals, the dom selectors with their literals, and
// the fingerprints referring to them. Patterns whose regex doesn't compile
// are dropped, as at run time. New decodes this into a CompiledFingerprints
// in one pass without parsing JSON or regexes (see decodeFingerprints); the
// regexes, selectors and literal matchers are built from it on first use.
//
// The data is a string constant rather than composite literals, which the
// compiler could initialize statically, because composite literals are much
// bigger: every string, slice and pointer in them is a header or address in
// the binary, which for the Workers build made the fingerprints cost 60%
// more (gzipped) than the JSON they're compiled from.
//
// The encoding is a sequence of uvarints and strings; see encoder. The
// uvarints, including the lengths of the strings, are in one string
// constant and the bytes of the strings in another, which compresses better
// than interleaving them. Decoded strings are substrings of the constant, so
// they cost no allocation. Lists that may be nil are encoded as their length
// plus one, with nil as zero. The data is:
//
//	counts: the number of patterns, selectors and apps, then the total
//	        lengths of the lists making up the apps (see fingerprintCounts)
//	patterns, each:
//	        flags (patternHasSrc etc.), [src], confidence, [version],
//	        [literal sets: count, then each set as a string list]
//	selectors, each:
//	        selector, literal sets or nil
//	apps, sorted by name, each:
//	        name, cats or nil, implies or nil, info,
//	        cookies, js and headers: count, then key and pattern index each
//	        html, script, scriptSrc: pattern index lists
//	        meta and dns: count, then key and pattern index list each
//	        robots, certIssuer, css: pattern index lists
//	        dom: count, then each rule's selector index and checks: count,
//	             then name and pattern index plus one (zero for nil) each
//
// Identical patterns and selectors are stored once and shared.

const (
	patternHasSrc = 1 << iota
	patternHasVersion
	patternHasLiterals
	patternSkipRegex
)

// GenerateFingerprintsSource returns the unformatted source of
// zz_generated_fingerprints.go for the given fingerprints and categories
// JSON. It is used by kitsune-gen.
func GenerateFingerprintsSource(fingerprintsJSON, categoriesJSON []byte) ([]byte, error) {
	if !unboundedRepeats {
		return nil, fmt.Errorf("KITSUNE_BOUNDED_REPEATS must not be set when generating fingerprints")
	}
	var fps Fingerprints
	if err := json.Unmarshal(fingerprintsJSON, &fps); err != nil {
		return nil, fmt.Errorf("fingerprints: %w", err)
	}
	if len(fps.Apps) == 0 {
		return nil, fmt.Errorf("no fingerprints found")
	}
	for name, fp := range fps.Apps {
		if strings.Contains(fp.Description+fp.Website+fp.Icon+fp.CPE, "\x00") {
			return nil, fmt.Errorf("%s: NUL in description, website, icon or cpe", name)
		}
	}
	categories, err := parseCategories(categoriesJSON)
	if err != nil {
		return nil, fmt.Errorf("categories: %w", err)
	}
	compiled, dropped := compileFingerprints(fps.Apps)

	// With KITSUNE_BOUNDED_REPEATS set, New derives the bounded patterns
	// from the generated ones (see withBoundedRepeats), so it would miss a
	// pattern that only compiles bounded.
	for _, raw := range dropped {
		regex := strings.Split(raw, "\\;")[0]
		if _, err := regexp.Compile("(?i)" + rewriteRegex(regex, true)); err == nil {
			return nil, fmt.Errorf("pattern %q only compiles with bounded repeats", raw)
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by kitsune-gen from assets/fingerprints_data.json and assets/categories_data.json. DO NOT EDIT.\n\n")
	buf.WriteString("//go:build !kitsune_gen_bootstrap\n\n")
	buf.WriteString("package profiler\n\n")
	buf.WriteString("var generatedCategories = map[int]categoryItem{\n")
	ids := make([]int, 0, len(categories))
	for id := range categories {
		ids = append(ids, id)
	}
	sort.Ints(ids)
	for _, id := range ids {
		fmt.Fprintf(&buf, "%d: {Name: %s, Priority: %d},\n", id, strconv.Quote(categories[id].Name), categories[id].Priority)
	}
	buf.WriteString("}\n\n")

	records := encodeFingerprints(compiled)
	buf.WriteString("// generatedFingerprints and generatedFingerprintText are the encoded\n")
	buf.WriteString("// fingerprints. See gen.go.\n")
	for _, c := range []struct {
		name  string
		field func(e *encoder) []byte
	}{
		{"generatedFingerprints", func(e *encoder) []byte { return e.buf }},
		{"generatedFingerprintText", func(e *encoder) []byte { return e.text }},
	} {
		fmt.Fprintf(&buf, "const %s = \"\" +\n", c.name)
		first := true
		for i := range records {
			if b := c.field(&records[i]); len(b) > 0 {
				if !first {
					buf.WriteString(" +\n")
				}
				first = false
				buf.WriteString(strconv.Quote(string(b)))
			}
		}
		buf.WriteString("\n\n")
	}

	// The caller formats the source with go/format, which isn't imported
	// here so as not to link it into every binary.
	return buf.Bytes(), nil
}

// encodeFingerprints encodes f, returning the encoding split into records
// (one per pattern, selector and app) so that the source has a line each.
func encodeFingerprints(f *CompiledFingerprints) []encoder {
	patterns := map[*ParsedPattern]int{}
	selectors := map[*domSelector]int{}
	var patternRecords, selectorRecords, appRecords []encoder
	patternIndex := map[string]int{}
	selectorIndex := map[string]int{}
	var counts fingerprintCounts

	pattern := func(p *ParsedPattern) int {
		if i, ok := patterns[p]; ok {
			return i
		}
		var e encoder
		flags := 0
		if p.src != "" {
			flags |= patternHasSrc
		}
		if p.Version != "" {
			flags |= patternHasVersion
		}
		if len(p.literals) > 0 {
			flags |= patternHasLiterals
		}
		if p.SkipRegex {
			flags |= patternSkipRegex
		}
		e.uint(flags)
		if p.src != "" {
			e.str(p.src)
		}
		e.uint(p.Confidence)
		if p.Version != "" {
			e.str(p.Version)
		}
		if len(p.literals) > 0 {
			e.uint(len(p.literals))
			for _, set := range p.literals {
				e.strs(set)
			}
		}
		i, ok := patternIndex[e.key()]
		if !ok {
			i = len(patternRecords)
			patternIndex[e.key()] = i
			patternRecords = append(patternRecords, e)
			counts.literalSets += len(p.literals)
			for _, set := range p.literals {
				counts.literals += len(set)
			}
		}
		patterns[p] = i
		return i
	}
	selector := func(sel *domSelector) int {
		if i, ok := selectors[sel]; ok {
			return i
		}
		var e encoder
		e.str(sel.selector)
		if sel.literals == nil {
			e.uint(0)
		} else {
			e.uint(len(sel.literals) + 1)
			for _, part := range sel.literals {
				e.strs(part)
			}
		}
		i, ok := selectorIndex[e.key()]
		if !ok {
			i = len(selectorRecords)
			selectorIndex[e.key()] = i
			selectorRecords = append(selectorRecords, e)
			counts.literalSets += len(sel.literals)
			for _, part := range sel.literals {
				counts.literals += len(part)
			}
		}
		selectors[sel] = i
		return i
	}

	for _, fp := range f.Apps {
		var e encoder
		e.str(fp.name)
		if fp.cats == nil {
			e.uint(0)
		} else {
			e.uint(len(fp.cats) + 1)
			for _, cat := range fp.cats {
				e.uint(cat)
			}
			counts.cats += len(fp.cats)
		}
		if fp.implies == nil {
			e.uint(0)
		} else {
			e.uint(len(fp.implies) + 1)
			for _, s := range fp.implies {
				e.str(s)
			}
			counts.implies += len(fp.implies)
		}
		e.str(fp.info)
		keyed := func(kps []keyedPattern) {
			e.uint(len(kps))
			for _, kp := range kps {
				e.str(kp.key)
				e.uint(pattern(kp.pattern))
			}
			counts.keyed += len(kps)
		}
		list := func(ps []*ParsedPattern) {
			e.uint(len(ps))
			for _, p := range ps {
				e.uint(pattern(p))
			}
			counts.patternRefs += len(ps)
		}
		multiKeyed := func(kps []keyedPatterns) {
			e.uint(len(kps))
			for _, kp := range kps {
				e.str(kp.key)
				list(kp.patterns)
			}
			counts.multiKeyed += len(kps)
		}
		keyed(fp.cookies)
		keyed(fp.js)
		keyed(fp.headers)
		list(fp.html)
		list(fp.script)
		list(fp.scriptSrc)
		multiKeyed(fp.meta)
		multiKeyed(fp.dns)
		list(fp.robots)
		list(fp.certIssuer)
		list(fp.css)
		e.uint(len(fp.dom))
		for _, rule := range fp.dom {
			e.uint(selector(rule.sel))
			e.uint(len(rule.checks))
			for _, check := range rule.checks {
				e.str(check.name)
				if check.pattern == nil {
					e.uint(0)
				} else {
					e.uint(pattern(check.pattern) + 1)
				}
			}
			counts.domChecks += len(rule.checks)
		}
		counts.domRules += len(fp.dom)
		appRecords = append(appRecords, e)
	}

	counts.patterns = len(patternRecords)
	counts.selectors = len(selectorRecords)
	counts.apps = len(appRecords)
	var header encoder
	for _, n := range counts.fields() {
		header.uint(*n)
	}
	records := []encoder{header}
	records = append(records, patternRecords...)
	records = append(records, selectorRecords...)
	return append(records, appRecords...)
}

// encoder appends uvarints to buf, and the bytes of strings to text.
type encoder struct {
	buf  []byte
	text []byte
}

// key returns a string identifying the encoding.
func (e *encoder) key() string {
	return strconv.Itoa(len(e.buf)) + ":" + string(e.buf) + string(e.text)
}

func (e *encoder) uint(v int) {
	if v < 0 {
		panic("negative value in fingerprint encoding")
	}
	e.buf = binary.AppendUvarint(e.buf, uint64(v))
}

func (e *encoder) str(s string) {
	e.uint(len(s))
	e.text = append(e.text, s...)
}

func (e *encoder) strs(list []string) {
	e.uint(len(list))
	for _, s := range list {
		e.str(s)
	}
}
