name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          args: --timeout 5m
          working-directory: .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Test
        run: go test ./... -v
      - name: Validate fingerprints_data.json
        run: |
          # Validate JSON syntax
          python3 -m json.tool assets/fingerprints_data.json > /dev/null
          echo "✅ JSON syntax is valid"
          
          # Check if file contains expected structure
          if ! grep -q '"apps"' assets/fingerprints_data.json; then
            echo "❌ Missing 'apps' key in fingerprints_data.json"
            exit 1
          fi
          echo "✅ JSON structure is valid" 